const images = {
    banner1: require("../images/banner-1.jpg"),
    banner2: require("../images/banner-2.jpg"),
    banner3: require("../images/banner-3.png"),
    american: require("../images/american.png"),
    burger: require("../images/burger.png"),
    pizza: require("../images/pizza.png"),
    drink: require("../images/drink.png"),
    beefGrill: require("../images/beef-grill.png"),
    chickenPiccata: require("../images/chicken-piccata.png"),
    chickenRomesco: require("../images/chicken-romesco.png"),
    chickenGrill: require("../images/chicken-grill.png"),
    salmonGrill: require("../images/salmon-grill.png"),
    salmonRomesco: require("../images/salmon-romesco.png"),
    burger1: require("../images/burger-1.png"),
    burger2: require("../images/burger-2.png"),
    burger3: require("../images/burger-3.png"),
    burger4: require("../images/burger-4.png"),
    burger5: require("../images/burger-5.png"),
    burger6: require("../images/burger-6.png"),
    pizza1: require("../images/pizza-1.png"),
    pizza2: require("../images/pizza-2.png"),
    pizza3: require("../images/pizza-3.png"),
    pizza4: require("../images/pizza-4.png"),
    pizza5: require("../images/pizza-5.png"),
    pizza6: require("../images/pizza-6.png"),
    cocacola: require("../images/cocacola.png"),
    pepsi: require("../images/pepsi.png"),
    quatro: require("../images/quatro.png"),
    sprite: require("../images/sprite.png")
}
export default images;